name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --all -- --check

  test-anodized-core:
    name: Test anodized-core
    runs-on: ubuntu-latest
    needs: fmt
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Clippy anodized-core
        run: cargo clippy -p anodized-core --all-targets -- -D warnings

      - name: Unit test anodized-core
        run: cargo test -p anodized-core --lib --no-fail-fast

  test-anodized:
    name: Test anodized with runtime behavior `${{ matrix.runtime }}`
    runs-on: ubuntu-latest
    needs: fmt
    strategy:
      matrix:
        include:
          - runtime: check-and-panic
          - runtime: check-and-print
          - runtime: no-check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Clippy anodized with runtime behavior `${{ matrix.runtime }}`
        run: cargo clippy -p anodized --all-targets --no-default-features --features "runtime-${{ matrix.runtime }}" -- -D warnings

      - name: Integration test anodized with runtime behavior `${{ matrix.runtime }}`
        run: cargo test -p anodized --tests --no-fail-fast --no-default-features --features "runtime-${{ matrix.runtime }}"

  test-anodized-fmt:
    name: Test anodized-fmt
    runs-on: ubuntu-latest
    needs: fmt
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Clippy anodized-fmt
        run: cargo clippy -p anodized-fmt --all-targets -- -D warnings

      - name: Unit and integration test anodized-fmt
        run: cargo test -p anodized-fmt --tests --no-fail-fast
